export const CATEGORY_DISPLAY: Record<string, { name: string; emoji: string; desc: string }> = {
  // Quizine (krogen)
  food:                  { name: 'Mat & Tillagning',        emoji: '🍳', desc: 'Tekniker & ingredienser' },
  drink:                 { name: 'Vin & Dryck',             emoji: '🍷', desc: 'Druvor, regioner, cocktails' },
  famous_profiles:       { name: 'Kända profiler',          emoji: '⭐', desc: 'Kockar & krogpersonligheter' },
  professional:          { name: 'Professionellt',          emoji: '💼', desc: 'Yrkeskunskap & karriär' },
  service_guests:        { name: 'Service & Gäster',        emoji: '🤵', desc: 'Etikett & scenarion' },
  industry_culture:      { name: 'Branschkultur',           emoji: '🍽️', desc: 'Historia & traditioner' },
  fun_reallife:          { name: 'Kul & Verklighet',        emoji: '😄', desc: 'Vardagen på krogen' },
  labor_law:             { name: 'Arbetsrätt',               emoji: '⚖️', desc: 'Lagar & avtal' },
  food_cost:             { name: 'Food Cost',                emoji: '💰', desc: 'Kalkyl & lönsamhet' },
  scheduling_labor:      { name: 'Schema & Bemanning',      emoji: '📅', desc: 'Planering & personal' },
  guest_psychology:      { name: 'Gästpsykologi',           emoji: '🧠', desc: 'Beteende & upplevelse' },
  service_pressure:      { name: 'Service Under Press',     emoji: '💪', desc: 'Stress & hantering' },
  // VOO (Vård & Omsorg)
  anatomy_body:          { name: 'Anatomi & Kroppen',       emoji: '🫀', desc: 'Organ, system & funktioner' },
  diagnoses_symptoms:    { name: 'Diagnoser & Symtom',      emoji: '🩺', desc: 'Sjukdom, symtom & diagnostik' },
  emergency_firstaid:    { name: 'Akut & Första hjälpen',   emoji: '🚨', desc: 'Akutvård, HLR & livräddning' },
  ethics_communication:  { name: 'Etik & Kommunikation',    emoji: '🤝', desc: 'Relationer, sekretess & bemötande' },
  infections_hygiene:    { name: 'Infektioner & Hygien',    emoji: '🦠', desc: 'Smittspridning & vårdhygien' },
  medical_history:       { name: 'Medicinsk Historia',      emoji: '📚', desc: 'Genombrott & milstolpar' },
  medications_pharma:    { name: 'Läkemedel & Farmakologi', emoji: '💊', desc: 'Preparat, mekanismer & biverkningar' },
  popculture_healthcare: { name: 'Populärkultur & Vård',    emoji: '🌟', desc: 'Kända läkare & vård i media' },
  psychiatry_psychology: { name: 'Psykiatri & Psykologi',   emoji: '🧠', desc: 'Psykiska tillstånd & behandling' },
  // IT (IT & Software)
  programming:           { name: 'Programmering',           emoji: '💻', desc: 'Kod, algoritmer & tekniker' },
  cloud_infra:           { name: 'Cloud & Infrastruktur',   emoji: '☁️', desc: 'DevOps, drift & nätverk' },
  cybersecurity:         { name: 'Cybersäkerhet',           emoji: '🔒', desc: 'Skydd, hot & sårbarheter' },
  databases:             { name: 'Databaser',               emoji: '🗄️', desc: 'SQL, NoSQL & datamodellering' },
  ai_ml:                 { name: 'AI & Maskininlärning',    emoji: '🧠', desc: 'Modeller, träning & tillämpningar' },
  operating_systems:     { name: 'Operativsystem',          emoji: '🖥️', desc: 'Linux, Windows & systemarkitektur' },
  web_apis:              { name: 'Webb & API:er',           emoji: '🌐', desc: 'HTTP, REST, frontend & backend' },
  app_development:       { name: 'Applikationsutveckling',  emoji: '📱', desc: 'Appar, frameworks & livscykel' },
}

export const ROMAN = ['I.', 'II.', 'III.']

export const CATEGORY_COLORS: Record<string, string> = {
  food: '#FF6B35',
  drink: '#8B2FC9',
  famous_profiles: '#E8B84B',
  professional: '#F7C948',
  service_guests: '#2EC4B6',
  industry_culture: '#9B5DE5',
  fun_reallife: '#F15BB5',
  labor_law: '#3A86FF',
  food_cost: '#06D6A0',
  scheduling_labor: '#FFB347',
  guest_psychology: '#FF6B9D',
  service_pressure: '#FF5555',
  anatomy_body: '#FF6B35',
  diagnoses_symptoms: '#9B5DE5',
  emergency_firstaid: '#FF5555',
  ethics_communication: '#2EC4B6',
  infections_hygiene: '#06D6A0',
  medical_history: '#E8B84B',
  medications_pharma: '#3A86FF',
  popculture_healthcare: '#F15BB5',
  psychiatry_psychology: '#8B2FC9',
  programming: '#00FF64',
  cloud_infra: '#00CC50',
  cybersecurity: '#00FF64',
  databases: '#00CC50',
  ai_ml: '#00FF64',
  operating_systems: '#00CC50',
  web_apis: '#00FF64',
  app_development: '#00CC50',
}
