[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/privacy"
  to = "/privacy/index.html"
  status = 200

[[redirects]]
  from = "/support"
  to = "/support/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
